### ISSUE TITLE
Position in error

### ISSUE THREAD

**Issue by flip111** [purescript-contrib/purescript-string-parsers#34]
At the moment the parser gives errors like `(Left Could not match character '"')`, would be handy to have position information about the error.

**Comment by newlandsvalley** [comment]
:+1:

**Comment by JordanMartinez** [comment]
Fixing this would require a breaking change due to the type signature of `runParser`. It also seems like `unParser` is what exposes the additional info so one can print their own parser. However, it's not user friendly to know that.

**Comment by JordanMartinez** [comment]
Nevermind. We could just add another variant of `runParser` that returns `Either String a`.
