### ISSUE TITLE
many1 should return NonEmptyList

### ISSUE THREAD

**Issue by rightfold** [purescript-contrib/purescript-string-parsers#36]
This makes the image closer to the codomain and is therefore easier and safer to use. Especially useful with the common use case of using foldl1 or foldr1 on the result.

**Comment by newlandsvalley** [comment]
Also the other combinators that parse one or more values - many1Till, sepBy1 etc.

**Comment by justinwoo** [comment]
Fixed by #41 right? Could be closed probably

**Comment by hdgarrood** [comment]
This was indeed fixed by #41, thanks @justinwoo
