### ISSUE TITLE
Port string-parsers syntax guide to this repo

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-string-parsers#51]
In my effort for doing jordanmartinez/purescript-jordans-reference#472, I would like to port the following file to this repo:
- [Syntax](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/22-Projects/src/01-Libraries/String-Parsers/01-Syntax.purs), which covers the main API here and a general idea for how it works.

What issues, if any, would arise if I do this?

**Comment by thomashoneyman** [comment]
Would you want to add this to the README, or just move the file here directly?

**Comment by JordanMartinez** [comment]
Since this repo's ReadMe doesn't include anything else, probably just the ReadMe. Then, it will appear on both the ReadMe and in its Pursuit docs
