### ISSUE TITLE
Not stack safe

### ISSUE THREAD

**Issue by nwolverson** [purescript-contrib/purescript-string-parsers#9]
A simple parser like `many (string "a")` will fail on an input of size 3000.

Due to lack of general TCO - not sure if it's inherent in the continuation based design of the `Parser` type or just the mutual recursion of things like `many`/`many1` and similar.

**Comment by paf31** [comment]
Hmm, I'm not sure if it's possible to get TCO given the CPS approach, as you say. I used CPS to be able to exit early in case of failure, but perhaps it's not worth it, and we should measure the performance difference.

**Comment by nwolverson** [comment]
Do you have an idea what would be a good example where "early exit" should work well? I've put together a version using a basic `Parser a = PosString -> Either Failure (Success a)`, for a tail recursive `many` success and failure cost the same (with `purescript-parsing` version much slower)
![parse 1](https://cloud.githubusercontent.com/assets/2770891/10119989/a497e674-649f-11e5-88ea-34407553bb5a.png)
![parsefail](https://cloud.githubusercontent.com/assets/2770891/10119990/a4d5f6e4-649f-11e5-8e45-8c800e09650c.png)
didn't really see a difference on a non-tailrec case
![benchfail](https://cloud.githubusercontent.com/assets/2770891/10120000/e1e0c0c8-649f-11e5-8403-e023d14ffbe3.png)
...backtracking with `try`?

**Comment by paf31** [comment]
Thanks for the analysis! Yes, I think the CPS approach shines when there is a lot of backtracking, since you don't have to pay for a bunch of unnecessary binds, but of course, you lose the tail recursive property :cry:

**Comment by paf31** [comment]
The latest version uses your `Parser a = PosString -> Either Failure (Success a)` model. Would you be interested in implementing `many` etc. in terms of the new `MonadRec` instance? (I think it should be possible)

**Comment by nwolverson** [comment]
Sure, I'll have a look
